defaults:
  - default
  - _self_

group_name: case33

train_config:
  alias: "dis_6t"
  save_path: reproduction
  alg: maddpg
  env: var_voltage_control
  mode: distributed

  scenario: case33_3min_final
  voltage_barrier_type: bowl

disturbances:
  - type: load_change
    is_random: True
    random_probability: 0.003
    random_duration: 200
    disturbance_args:
      multiplier: 6
