defaults:
  - default
  - _self_

group_name: case33

train_config:
  alias: "dis_pv_stop"
  save_path: reproduction
  alg: maddpg
  env: var_voltage_control
  mode: distributed

  scenario: case33_3min_final
  voltage_barrier_type: bowl

disturbances:
  - type: pv_stop
    is_random: True
    random_probability: 0.003
    random_duration: 200
    disturbance_args:
      pv_id: [0,1,2,3,4,5]
