defaults:
  - default
  - _self_

run_group: latest
save_group: latest

description: 补充训练ippo和coma

steps:
  - type: train
    config_name: case33
    multirun: True
    args:
      - train_config.alg=ippo,coma
      - train_config.alias=original,dis_new_q_weight_0.1_10t
  - type: eval
    config_name: case335
    multirun: True
    args:
      - eval_config.alg=ippo,coma
      - eval_config.alias=original,dis_new_q_weight_0.1_10t
